#!/bin/bash

# 3. Write a custom script
# Shows some general info about the date, system uptime, latest logins and memory/disk usage


date
echo "uptime:"	
uptime
echo "Currently connected:"
w
echo "--------------------"
echo "Last logins:"
last -a | head -3
echo "--------------------"
echo "Disk and memory usage:"
df -h | xargs | awk '{print "Free/total disk: " $11 " / " $9}'
free -m | xargs | awk '{print "Free/total memory: " $17 " / " $8 " MB"}'
echo "--------------------" 
